title: jekyll-rtd-theme
description: Just another documentation theme compatible with GitHub Pages

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
- jemoji
- jekyll-avatar
- jekyll-mentions
- jekyll-readme-index
- jekyll-commonmark
- jekyll-commonmark-ghpages
- jekyll-default-layout
- jekyll-feed
- jekyll-github-metadata
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-titles-from-headings

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
